version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_USER: library-api
      POSTGRES_PASSWORD: library-api
      POSTGRES_DB: library-api
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - local
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - local
    restart: unless-stopped

networks:
  local:
    driver: bridge
